spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

docker:
  email: hwryu990927@gmail.com
  password: hwryu990927!
  username: uhanuu
  host: tcp://127.0.0.1:2376


compile:
  path: /Users/ryu/goorm/ide/webide/compile/